import { Injectable } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { Prisma } from "../../generated/prisma/client";
import { apiException } from "../common/http";
import { PrismaService } from "../common/prisma.service";

type Application = { displayName: string; phone: string; identityNumber?: string; bio?: string; applicationNote: string; bankName: string; bankAccountName: string; bankAccountNumber: string };
type Submission = { title: string; brandId?: string; proposedBrand?: string; categoryId: string; conditionLabel: "PRISTINE" | "EXCELLENT" | "VERY_GOOD" | "GOOD"; completeness: string; flawNotes?: string; description: string; expectedPrice: number };

@Injectable()
export class SellerService {
  constructor(private readonly prisma: PrismaService) {}
  profile(userId: string) { return this.prisma.sellerProfile.findFirst({ where: { userId, deletedAt: null } }); }
  async requireProfile(userId: string, approved = true) { const seller = await this.profile(userId); if (!seller) apiException(403, "SELLER_PROFILE_REQUIRED", "Ajukan akun seller terlebih dahulu."); if (approved && seller.status !== "APPROVED") apiException(403, "SELLER_NOT_APPROVED", "Akun seller belum disetujui."); return seller; }
  private activity(tx: Prisma.TransactionClient, input: { sellerId: string; actorUserId?: string; action: string; entityType: string; entityId?: string; metadata?: Prisma.InputJsonValue; moneyBefore?: Prisma.Decimal; moneyAfter?: Prisma.Decimal }) { return tx.sellerActivityLog.create({ data: input }); }

  async apply(userId: string, data: Application) {
    const existing = await this.prisma.sellerProfile.findUnique({ where: { userId } });
    if (existing && existing.status !== "REJECTED") apiException(409, "APPLICATION_EXISTS", "Pengajuan seller sudah tersedia.");
    const seller = await this.prisma.$transaction(async (tx) => { const profile = existing ? await tx.sellerProfile.update({ where: { id: existing.id }, data: { ...data, identityNumber: data.identityNumber || null, bio: data.bio || null, status: "PENDING", rejectionReason: null, reviewedAt: null, reviewedById: null } }) : await tx.sellerProfile.create({ data: { ...data, userId, identityNumber: data.identityNumber || null, bio: data.bio || null } }); await this.activity(tx, { sellerId: profile.id, actorUserId: userId, action: "SELLER_APPLICATION_SUBMITTED", entityType: "SellerProfile", entityId: profile.id }); return profile; });
    return { id: seller.id, status: seller.status };
  }
  async updateProfile(userId: string, data: Omit<Application, "identityNumber" | "applicationNote">) { const seller = await this.requireProfile(userId, false); await this.prisma.$transaction(async (tx) => { await tx.sellerProfile.update({ where: { id: seller.id }, data: { ...data, bio: data.bio || null } }); await this.activity(tx, { sellerId: seller.id, actorUserId: userId, action: "SELLER_PROFILE_UPDATED", entityType: "SellerProfile", entityId: seller.id }); }); return { id: seller.id }; }
  async createSubmission(userId: string, data: Submission) { const seller = await this.requireProfile(userId); const created = await this.prisma.$transaction(async (tx) => { const item = await tx.consignmentSubmission.create({ data: { ...data, submissionNumber: `CS-${Date.now()}-${randomUUID().slice(0, 5).toUpperCase()}`, sellerId: seller.id, brandId: data.brandId || null, proposedBrand: data.proposedBrand || null, flawNotes: data.flawNotes || null } }); await this.activity(tx, { sellerId: seller.id, actorUserId: userId, action: "SUBMISSION_DRAFT_CREATED", entityType: "ConsignmentSubmission", entityId: item.id }); return item; }); return { id: created.id, submissionNumber: created.submissionNumber }; }
  async updateSubmission(userId: string, id: string, data: Submission) { const seller = await this.requireProfile(userId); const current = await this.prisma.consignmentSubmission.findFirst({ where: { id, sellerId: seller.id } }); if (!current) apiException(404, "NOT_FOUND", "Pengajuan tidak ditemukan."); if (!(["DRAFT", "NEEDS_REVISION"] as string[]).includes(current.status)) apiException(409, "SUBMISSION_LOCKED", "Pengajuan tidak dapat diedit pada status ini."); await this.prisma.$transaction(async (tx) => { await tx.consignmentSubmission.update({ where: { id }, data: { ...data, brandId: data.brandId || null, proposedBrand: data.proposedBrand || null, flawNotes: data.flawNotes || null, version: { increment: 1 } } }); await this.activity(tx, { sellerId: seller.id, actorUserId: userId, action: "SUBMISSION_UPDATED", entityType: "ConsignmentSubmission", entityId: id }); }); return { id }; }
  async transition(userId: string, id: string, input: { status: "SUBMITTED" | "WAITING_FOR_ITEM" | "CANCELLED"; decision?: "ACCEPTED" | "REJECTED"; reason?: string }) { const seller = await this.requireProfile(userId); const current = await this.prisma.consignmentSubmission.findFirst({ where: { id, sellerId: seller.id }, include: { images: true } }); if (!current) apiException(404, "NOT_FOUND", "Pengajuan tidak ditemukan."); let next = input.status; if (current.status === "APPROVED") { if (!input.decision) apiException(422, "DECISION_REQUIRED", "Terima atau tolak estimasi harga."); next = input.decision === "ACCEPTED" ? "WAITING_FOR_ITEM" : "CANCELLED"; } const allowed: Record<string, string[]> = { DRAFT: ["SUBMITTED", "CANCELLED"], NEEDS_REVISION: ["SUBMITTED", "CANCELLED"], APPROVED: ["WAITING_FOR_ITEM", "CANCELLED"] }; if (!allowed[current.status]?.includes(next)) apiException(409, "INVALID_SUBMISSION_TRANSITION", "Perubahan status tidak valid."); if (next === "SUBMITTED" && current.images.length < 3) apiException(422, "IMAGES_REQUIRED", "Tambahkan minimal 3 foto sebelum mengirim pengajuan."); const updated = await this.prisma.$transaction(async (tx) => { const result = await tx.consignmentSubmission.update({ where: { id }, data: { status: next, priceDecision: input.decision ?? current.priceDecision, agreedPrice: input.decision === "ACCEPTED" ? current.estimatedPrice : current.agreedPrice, cancelledAt: next === "CANCELLED" ? new Date() : current.cancelledAt, version: { increment: 1 } } }); await this.activity(tx, { sellerId: seller.id, actorUserId: userId, action: `SUBMISSION_${next}`, entityType: "ConsignmentSubmission", entityId: id, metadata: { from: current.status, to: next } }); return result; }); return { id, status: updated.status }; }

  async overview(userId: string) { const seller = await this.requireProfile(userId); const [submissions, listed, sold, commissions] = await Promise.all([this.prisma.consignmentSubmission.count({ where: { sellerId: seller.id } }), this.prisma.consignmentSubmission.count({ where: { sellerId: seller.id, status: "LISTED" } }), this.prisma.consignmentSubmission.count({ where: { sellerId: seller.id, status: { in: ["SOLD", "COMPLETED"] } } }), this.prisma.commission.findMany({ where: { submission: { sellerId: seller.id, status: "COMPLETED" }, payoutItem: null, sellerNetAmount: { not: null } }, select: { sellerNetAmount: true } })]); return { seller, submissions, listed, sold, balance: commissions.reduce((sum, item) => sum + Number(item.sellerNetAmount), 0) }; }
  async submissions(userId: string) { const seller = await this.requireProfile(userId); return this.prisma.consignmentSubmission.findMany({ where: { sellerId: seller.id }, include: { brand: true, images: { take: 1 } }, orderBy: { updatedAt: "desc" } }); }
  async submission(userId: string, id: string) { const seller = await this.requireProfile(userId); return this.prisma.consignmentSubmission.findFirst({ where: { id, sellerId: seller.id }, include: { brand: true, category: true, images: { orderBy: { sortOrder: "asc" } }, inspections: { orderBy: { inspectedAt: "desc" } }, commission: true, product: true } }); }
  async listed(userId: string) { const seller = await this.requireProfile(userId); return this.prisma.consignmentSubmission.findMany({ where: { sellerId: seller.id, status: "LISTED" }, include: { product: true }, orderBy: { listedAt: "desc" } }); }
  async sales(userId: string) { const seller = await this.requireProfile(userId); return this.prisma.consignmentSubmission.findMany({ where: { sellerId: seller.id, status: { in: ["SOLD", "COMPLETED"] } }, include: { commission: true }, orderBy: { soldAt: "desc" } }); }
  async balance(userId: string) { const seller = await this.requireProfile(userId); const [eligible, pending] = await Promise.all([this.prisma.commission.findMany({ where: { submission: { sellerId: seller.id, status: "COMPLETED" }, sellerNetAmount: { not: null }, payoutItem: null }, include: { submission: true } }), this.prisma.payout.aggregate({ where: { sellerId: seller.id, status: { in: ["REQUESTED", "PROCESSING"] } }, _sum: { amount: true } })]); return { eligible, pending: Number(pending._sum.amount ?? 0), available: eligible.reduce((sum, item) => sum + Number(item.sellerNetAmount), 0) }; }
  async payouts(userId: string) { const seller = await this.requireProfile(userId); return this.prisma.payout.findMany({ where: { sellerId: seller.id }, include: { _count: { select: { items: true } } }, orderBy: { requestedAt: "desc" } }); }
  options() { return Promise.all([this.prisma.category.findMany({ where: { isActive: true, deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } }), this.prisma.brand.findMany({ where: { isActive: true, deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } })]).then(([categories, brands]) => ({ categories, brands })); }
  async requestPayout(userId: string, commissionIds: string[]) { const seller = await this.requireProfile(userId); if (!seller.bankName || !seller.bankAccountName || !seller.bankAccountNumber) apiException(422, "BANK_ACCOUNT_REQUIRED", "Lengkapi rekening payout."); const commissions = await this.prisma.commission.findMany({ where: { id: { in: commissionIds }, submission: { sellerId: seller.id, status: "COMPLETED" }, sellerNetAmount: { not: null }, payoutItem: null } }); if (commissions.length !== new Set(commissionIds).size) apiException(409, "PAYOUT_ITEM_NOT_ELIGIBLE", "Terdapat item yang belum eligible atau sudah dicairkan."); const amount = commissions.reduce((sum, item) => sum.add(item.sellerNetAmount!), new Prisma.Decimal(0)); const payout = await this.prisma.payout.create({ data: { payoutNumber: `PO-${Date.now()}-${randomUUID().slice(0, 5).toUpperCase()}`, sellerId: seller.id, amount, bankSnapshot: { bankName: seller.bankName, accountName: seller.bankAccountName, accountLast4: seller.bankAccountNumber.slice(-4) }, items: { create: commissions.map((item) => ({ commissionId: item.id, amount: item.sellerNetAmount! })) } } }); return { id: payout.id, payoutNumber: payout.payoutNumber, amount: amount.toNumber() }; }
  async addImage(userId: string, submissionId: string, file: { buffer: Buffer; mimetype: string; size: number }) {
    const seller = await this.requireProfile(userId);
    const submission = await this.prisma.consignmentSubmission.findFirst({ where: { id: submissionId, sellerId: seller.id }, include: { _count: { select: { images: true } } } });
    if (!submission) apiException(404, "NOT_FOUND", "Pengajuan tidak ditemukan.");
    if (!["DRAFT", "NEEDS_REVISION"].includes(submission.status)) apiException(409, "SUBMISSION_LOCKED", "Foto tidak dapat diubah.");
    if (submission._count.images >= 10) apiException(422, "IMAGE_LIMIT", "Maksimal 10 foto.");
    const extension = ({ "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp" } as Record<string, string>)[file.mimetype];
    if (!extension || file.size > 5 * 1024 * 1024) apiException(422, "IMAGE_INVALID", "File gambar tidak memenuhi persyaratan.");
    const directory = join(process.cwd(), "public", "uploads", "consignments"); await mkdir(directory, { recursive: true }); const name = `${randomUUID()}${extension}`; await writeFile(join(directory, name), file.buffer);
    const base = (process.env.BACKEND_PUBLIC_URL ?? `http://localhost:${process.env.PORT ?? 4000}`).replace(/\/$/, "");
    return this.prisma.consignmentImage.create({ data: { submissionId, url: `${base}/uploads/consignments/${name}`, storageKey: name, mimeType: file.mimetype, sizeBytes: file.size, width: 1200, height: 1200, alt: `${submission.title} consignment photo`, sortOrder: submission._count.images, isPrimary: submission._count.images === 0 } });
  }
}
export type { Application, Submission };
