import { Injectable } from "@nestjs/common";
import { PrismaService } from "../common/prisma.service";
import { apiException } from "../common/http";

const TAKE = 20;
@Injectable()
export class AdminService {
  constructor(private readonly prisma: PrismaService) {}
  async view(view: string, query: Record<string, string | undefined>) {
    const page = Math.max(1, Number(query.page) || 1); const skip = (page - 1) * TAKE; const q = query.q?.trim(); const status = query.status; const stock = query.stock;
    if (view === "layout") { const [pendingOrders, lowStock] = await Promise.all([this.prisma.order.count({ where: { status: "PENDING_PAYMENT" } }), this.prisma.inventory.count({ where: { quantity: { lte: 2 } } })]); return { pendingOrders, lowStock }; }
    if (view === "dashboard") { const [sales, totalOrders, totalCustomers, pendingOrders, lowStock, recentOrders, orderItems] = await Promise.all([this.prisma.order.findMany({ where: { paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] } }, select: { grandTotal: true, placedAt: true } }), this.prisma.order.count(), this.prisma.user.count({ where: { role: "CUSTOMER", deletedAt: null } }), this.prisma.order.count({ where: { status: "PENDING_PAYMENT" } }), this.prisma.inventory.findMany({ where: { quantity: { lte: 2 } }, include: { variant: { include: { product: { include: { brand: true } } } } }, orderBy: { quantity: "asc" }, take: 6 }), this.prisma.order.findMany({ orderBy: { placedAt: "desc" }, take: 6, select: { id: true, orderNumber: true, customerName: true, status: true, grandTotal: true, placedAt: true } }), this.prisma.orderItem.findMany({ where: { order: { paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] } } }, include: { variant: { include: { product: { include: { brand: true } } } } }, take: 1000 })]); return { sales, totalOrders, totalCustomers, pendingOrders, lowStock, recentOrders, orderItems }; }
    if (view === "options") { const [categories, brands] = await Promise.all([this.prisma.category.findMany({ where: { isActive: true, deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } }), this.prisma.brand.findMany({ where: { isActive: true, deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); return { categories, brands }; }
    if (view === "products") { const where = { deletedAt: null, ...(status ? { status: status as "DRAFT" | "ACTIVE" | "ARCHIVED" } : {}), ...(stock === "low" ? { variants: { some: { inventory: { is: { quantity: { lte: 2 } } } } } } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { baseSku: { contains: q, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.product.findMany({ where, include: { brand: true, category: true, variants: { include: { inventory: true } }, images: { where: { isPrimary: true }, take: 1 } }, orderBy: { updatedAt: "desc" }, skip, take: TAKE }), this.prisma.product.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "orders") { const where = { ...(status ? { status: status as never } : {}), ...(q ? { OR: [{ orderNumber: { contains: q, mode: "insensitive" as const } }, { customerName: { contains: q, mode: "insensitive" as const } }, { customerEmail: { contains: q, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.order.findMany({ where, include: { _count: { select: { items: true } } }, orderBy: { placedAt: "desc" }, skip, take: TAKE }), this.prisma.order.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "customers") { const where = { deletedAt: null, ...(status ? { isActive: status === "active" } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { email: { contains: q, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.user.findMany({ where, include: { _count: { select: { orders: true } } }, orderBy: { createdAt: "desc" }, skip, take: TAKE }), this.prisma.user.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (["categories", "brands", "vouchers"].includes(view)) { if (view === "categories") { const [items, total] = await Promise.all([this.prisma.category.findMany({ where: { deletedAt: null, ...(q ? { name: { contains: q, mode: "insensitive" } } : {}) }, include: { parent: true, _count: { select: { products: true } } }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }], skip, take: TAKE }), this.prisma.category.count({ where: { deletedAt: null } })]); return { items, total, page, pageSize: TAKE }; } if (view === "brands") { const [items, total] = await Promise.all([this.prisma.brand.findMany({ where: { deletedAt: null, ...(q ? { name: { contains: q, mode: "insensitive" } } : {}) }, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" }, skip, take: TAKE }), this.prisma.brand.count({ where: { deletedAt: null } })]); return { items, total, page, pageSize: TAKE }; } const [items, total] = await Promise.all([this.prisma.voucher.findMany({ where: q ? { OR: [{ code: { contains: q, mode: "insensitive" } }, { name: { contains: q, mode: "insensitive" } }] } : {}, orderBy: { createdAt: "desc" }, skip, take: TAKE }), this.prisma.voucher.count()]); return { items, total, page, pageSize: TAKE }; }
    if (view === "content") { const [sections, banners, testimonials] = await Promise.all([this.prisma.homepageSection.findMany({ orderBy: { sortOrder: "asc" } }), this.prisma.banner.findMany({ where: { deletedAt: null }, orderBy: { sortOrder: "asc" } }), this.prisma.testimonial.findMany({ where: { deletedAt: null }, orderBy: { sortOrder: "asc" } })]); return { sections, banners, testimonials }; }
    if (view === "inventory") { const where = q ? { variant: { OR: [{ sku: { contains: q, mode: "insensitive" as const } }, { product: { name: { contains: q, mode: "insensitive" as const } } }] } } : {}; const [records, total] = await Promise.all([this.prisma.inventory.findMany({ where, include: { variant: { include: { product: { select: { id: true, name: true } } } } }, orderBy: { updatedAt: "desc" }, skip, take: TAKE }), this.prisma.inventory.count({ where })]); const items = records.map((record) => ({ id: record.id, productId: record.variant.product.id, productName: record.variant.product.name, variantId: record.variant.id, sku: record.variant.sku, variantName: record.variant.name, color: record.variant.color, size: record.variant.size, quantity: record.quantity, reserved: record.reserved, available: Math.max(0, record.quantity - record.reserved), lowStockAt: record.lowStockAt, status: record.quantity - record.reserved <= record.lowStockAt ? "LOW_STOCK" : "IN_STOCK", updatedAt: record.updatedAt })); return { items, total, page, pageSize: TAKE }; }
    if (view === "shipments") { const where = { ...(status ? { status: status as never } : {}), ...(q ? { OR: [{ trackingNumber: { contains: q, mode: "insensitive" as const } }, { order: { orderNumber: { contains: q, mode: "insensitive" as const } } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.shipment.findMany({ where, include: { order: { select: { id: true, orderNumber: true, customerName: true } } }, orderBy: { updatedAt: "desc" }, skip, take: TAKE }), this.prisma.shipment.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "audit") { const where = q ? { OR: [{ action: { contains: q, mode: "insensitive" as const } }, { entityType: { contains: q, mode: "insensitive" as const } }] } : {}; const [items, total] = await Promise.all([this.prisma.auditLog.findMany({ where, include: { user: true }, orderBy: { createdAt: "desc" }, skip, take: TAKE }), this.prisma.auditLog.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "sellers") { const where = { deletedAt: null, ...(status ? { status: status as never } : {}), ...(q ? { OR: [{ displayName: { contains: q, mode: "insensitive" as const } }, { user: { email: { contains: q, mode: "insensitive" as const } } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.sellerProfile.findMany({ where, include: { user: true, _count: { select: { submissions: true, payouts: true } } }, orderBy: { createdAt: "desc" }, skip, take: TAKE }), this.prisma.sellerProfile.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "submissions") { const where = { ...(status ? { status: status as never } : {}), ...(q ? { OR: [{ title: { contains: q, mode: "insensitive" as const } }, { submissionNumber: { contains: q, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([this.prisma.consignmentSubmission.findMany({ where, include: { seller: true, _count: { select: { images: true } } }, orderBy: { updatedAt: "desc" }, skip, take: TAKE }), this.prisma.consignmentSubmission.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "payouts") { const where = { ...(status ? { status: status as never } : {}), ...(q ? { payoutNumber: { contains: q, mode: "insensitive" as const } } : {}) }; const [items, total] = await Promise.all([this.prisma.payout.findMany({ where, include: { seller: true, _count: { select: { items: true } } }, orderBy: { requestedAt: "desc" }, skip, take: TAKE }), this.prisma.payout.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "seller-activity") { const where = q ? { OR: [{ action: { contains: q, mode: "insensitive" as const } }, { seller: { displayName: { contains: q, mode: "insensitive" as const } } }] } : {}; const [items, total] = await Promise.all([this.prisma.sellerActivityLog.findMany({ where, include: { seller: true, actor: true }, orderBy: { createdAt: "desc" }, skip, take: TAKE }), this.prisma.sellerActivityLog.count({ where })]); return { items, total, page, pageSize: TAKE }; }
    if (view === "search") { if (!q || q.length < 2) return { query: q ?? "", products: [], orders: [], customers: [], sellers: [] }; const [products, orders, customers, sellers] = await Promise.all([this.prisma.product.findMany({ where: { deletedAt: null, OR: [{ name: { contains: q, mode: "insensitive" } }, { baseSku: { contains: q, mode: "insensitive" } }] }, select: { id: true, name: true, baseSku: true, status: true }, take: 10 }), this.prisma.order.findMany({ where: { OR: [{ orderNumber: { contains: q, mode: "insensitive" } }, { customerName: { contains: q, mode: "insensitive" } }, { customerEmail: { contains: q, mode: "insensitive" } }] }, select: { id: true, orderNumber: true, customerName: true, status: true, grandTotal: true }, take: 10 }), this.prisma.user.findMany({ where: { deletedAt: null, OR: [{ name: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] }, select: { id: true, name: true, email: true, role: true, isActive: true }, take: 10 }), this.prisma.sellerProfile.findMany({ where: { deletedAt: null, OR: [{ displayName: { contains: q, mode: "insensitive" } }, { user: { email: { contains: q, mode: "insensitive" } } }] }, select: { id: true, displayName: true, status: true, user: { select: { email: true } } }, take: 10 })]); return { query: q, products, orders, customers, sellers }; }
    if (view === "reports") { const from = query.from && !Number.isNaN(Date.parse(query.from)) ? new Date(query.from) : new Date(Date.now() - 30 * 86_400_000); const to = query.to && !Number.isNaN(Date.parse(query.to)) ? new Date(query.to) : new Date(); const paidWhere = { placedAt: { gte: from, lte: to }, paymentStatus: { in: ["PAID", "PARTIALLY_REFUNDED"] as ("PAID" | "PARTIALLY_REFUNDED")[] } }; const [paidOrders, totalOrders, newCustomers, orderStatuses, topItems, lowStock] = await Promise.all([this.prisma.order.findMany({ where: paidWhere, select: { grandTotal: true, placedAt: true } }), this.prisma.order.count({ where: { placedAt: { gte: from, lte: to } } }), this.prisma.user.count({ where: { role: "CUSTOMER", createdAt: { gte: from, lte: to }, deletedAt: null } }), this.prisma.order.groupBy({ by: ["status"], where: { placedAt: { gte: from, lte: to } }, _count: { _all: true } }), this.prisma.orderItem.findMany({ where: { order: paidWhere }, select: { productName: true, quantity: true, lineTotal: true }, take: 2000 }), this.prisma.inventory.count({ where: { quantity: { lte: 2 } } })]); const revenue = paidOrders.reduce((sum, order) => sum + Number(order.grandTotal), 0); const productMap = new Map<string, { productName: string; quantity: number; revenue: number }>(); for (const item of topItems) { const current = productMap.get(item.productName) ?? { productName: item.productName, quantity: 0, revenue: 0 }; current.quantity += item.quantity; current.revenue += Number(item.lineTotal); productMap.set(item.productName, current); } return { period: { from, to }, summary: { revenue, paidOrders: paidOrders.length, totalOrders, newCustomers, lowStock }, orderStatuses: orderStatuses.map((item) => ({ status: item.status, count: item._count._all })), topProducts: [...productMap.values()].sort((a, b) => b.revenue - a.revenue).slice(0, 10) }; }
    apiException(404, "NOT_FOUND", "Admin view tidak ditemukan.");
  }
  async detail(resource: string, id: string) { if (resource === "products") return this.prisma.product.findUnique({ where: { id }, include: { images: { orderBy: { sortOrder: "asc" } }, variants: { include: { inventory: true } } } }); if (resource === "orders") return this.prisma.order.findUnique({ where: { id }, include: { user: true, items: true, payments: { orderBy: { createdAt: "desc" } }, shipments: { orderBy: { createdAt: "desc" } }, voucherUsages: { include: { voucher: true } } } }); if (resource === "customers") return this.prisma.user.findUnique({ where: { id }, include: { addresses: true, orders: { orderBy: { placedAt: "desc" }, take: 10 }, _count: { select: { orders: true, reviews: true } } } }); if (resource === "sellers") return this.prisma.sellerProfile.findUnique({ where: { id }, include: { user: true, submissions: { orderBy: { updatedAt: "desc" }, take: 10 }, payouts: { orderBy: { requestedAt: "desc" }, take: 10 } } }); if (resource === "submissions") return this.prisma.consignmentSubmission.findUnique({ where: { id }, include: { seller: { include: { user: true } }, brand: true, category: true, images: { orderBy: { sortOrder: "asc" } }, inspections: { orderBy: { inspectedAt: "desc" } }, commission: true, product: true } }); apiException(404, "NOT_FOUND", "Resource tidak ditemukan."); }
}
